
Dataset not found ⚠️, missing paths ['/home/nurbanu/roverTask/dataset/valid/images']
Traceback (most recent call last):
  File "/home/arman/study/roverTask/yolov5/train.py", line 986, in <module>
    main(opt)
  File "/home/arman/study/roverTask/yolov5/train.py", line 688, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/arman/study/roverTask/yolov5/train.py", line 203, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/arman/study/roverTask/yolov5/utils/general.py", line 564, in check_dataset
    raise Exception("Dataset not found ❌")
Exception: Dataset not found ❌
